# Generated by Django 4.1.5 on 2023-01-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Address',
            field=models.CharField(max_length=50, verbose_name='Toilet Address'),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Mobile_No',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Toilet Mob No'),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Ph_No',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Toilet Ph No'),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_Price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Toilet Price'),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_lat',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Toilet Lat'),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_long',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Toilet Long'),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_name',
            field=models.CharField(max_length=100, verbose_name='Toilet Name'),
        ),
        migrations.AlterField(
            model_name='hostel_info',
            name='Hostel_type',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Toilet Type'),
        ),
    ]
